### ISSUE TITLE
what is the reason for the error?

### ISSUE THREAD

**Issue by MinistrBob** [actmd/zoomus#14]
what is the reason for the error?

This code

`from zoomus import ZoomClient
import json

client = ZoomClient('nlPuETI4SNCVK7r5Lkl8EQ', 'gluuFR42imJ96VFpkmy1Yve0DBGeHUwwBZDG')

for user in json.loads(client.user.list())['users']:
    user_id = user['id']
    print(client.users.list())`

this error

`Traceback (most recent call last):
  File "C:/MyGit/GivinToolsPython/zoomtest.py", line 8, in <module>
    for user in json.loads(client.user.list())['users']:
  File "C:\Program Files\Python37\lib\json\__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not Response`

**Comment by prschmid** [comment]
Hi @MinistrBob!

The problem is that there is a slight error in the documentation which was fixed up on the develop branch but not on yet on master. Please see https://github.com/actmd/zoomus/issues/2

**Comment by MinistrBob** [comment]
I do that:
`from zoomus import ZoomClient
import json

client = ZoomClient('nlPuETI4SNCVK7r5Lkl8EQ', 'gluuFR42imJ96VFpkmy1Yve0DBGeHUwwBZDG')

for user in json.loads(client.user.list().content)['users']:
    user_id = user['id']
    print(client.meeting.list(host_id=user_id))`

Anyway error:
`C:\MyGit\GivinToolsPython\env\Scripts\python.exe C:/MyGit/GivinToolsPython/zoomtest.py
Traceback (most recent call last):
  File "C:/MyGit/GivinToolsPython/zoomtest.py", line 6, in <module>
    for user in json.loads(client.user.list().content)['users']:
KeyError: 'users'

Process finished with exit code 1`

If I run code in debug, when getting  client.user.list().content  = b'{"code":124,"message":"Invalid access token."}'

Where should I get API_KEY & API_SECRET ?    I get it in zoom profile (see.picture)

 
![image](https://user-images.githubusercontent.com/5189583/58873280-addf7a80-86ce-11e9-8f76-9adced3aec16.png)

**Comment by MohsenWaleed** [comment]
Hi @MinistrBob 

I'm getting the same error, How you solve it?

**Comment by MinistrBob** [comment]
(Unfortunately, I can’t insert screenshots here :(  )
You need to use JWT authorization (I use this one; here it’s enough to have API_KEY and API_SECRET to fulfill API requests).

Create an application in the Zoom development center with JWT authorization - https://marketplace.zoom.us/user/build

In the application itself, on the App Credentials tab, there are API_KEY and API_SECRET so they are used

Further I use zoomus here is an example code.

```
from zoomus import ZoomClient
import json

#client = ZoomClient('API_KEY', 'API_SECRET')
client = ZoomClient('7dtr8NY67777777770TQnfeQ', 'TyAcDcUBO2777777777Q71vAsOv')

print(client.user.list().content)
print(json.loads(client.user.list().content))
print(json.loads(client.user.list().content)['users'])
print("="*60)
for user in json.loads(client.user.list().content)['users']:
    print(user)
    user_id = user['id']
    print(client.meeting.list(host_id=user_id))
```

It would be great if it were in README.MD zoomus

**Comment by MohsenWaleed** [comment]
Many Thanks for your reply @MinistrBob. It's very helpful.
