### ISSUE TITLE
Not understanding how to use these methods ?

### ISSUE THREAD

**Issue by SachinDG** [actmd/zoomus#15]
Not able to understand how to use these methods for eg. client.user.get_by_email()?
Basically, I am trying to write a cronjob/schedule job for my Django web app which will transfer zoom recording to our s3 bucket in every two hours, but I am unable to understand these methods.

My cronjob code is like below:-

from django_cron import CronJobBase, Schedule
from zoomus import ZoomClient

class zoomrecordingtransfer(CronJobBase):
    RUN_EVERY_MINS = 120 # every 2 hours

    schedule = Schedule(run_every_mins=RUN_EVERY_MINS)
    code = 'zoomtransferjob.zoom_transfer_cron_job'    # a unique code

    def do(self):
        client = ZoomClient('sxxxxxxxxxTbYug', 'axxxxxxxxxxxxxxxxxxxxtgsT1')
        temp = client.user.get_by_email('abc@gmail.com')
        print(temp)
 
Can anyone help me out regarding how should I use these methods as I am not getting any output with "client.user.get_by_email('abc@gmail.com')" in print statement?

**Comment by prschmid** [comment]
@SachinDG sorry to hear about your troubles. My first guess is that you are using the V2 API from zoom and currently the master branch of this library only supports the V1 Zoom API. There is an open PR (https://github.com/actmd/zoomus/pull/11) where this functionality will be added. I was the one holding it back due to time constraints on my side, but hopefully we can get that merged soon.

**Comment by SachinDG** [comment]
Hi @prschmid, it's great to hear from you about it. But I am using v1 API as we have zoom v1 integrated with our app. Can you help me with some documentation or any idea to deal with it.

**Comment by prschmid** [comment]
If you take look at the code, all that's happening under the hood is that we are using the `requests` library to call the "/user/getbyemail" endpoint (via a POST) from Zoom. Assuming I'm not misunderstanding my own code that I wrote a couple years ago, the response from that method should be a `requests.Response` object that you should be able to inspect. Let me know if that helps.

**Comment by SachinDG** [comment]
Well, thank you for your help @prschmid.
