### ISSUE TITLE
Proposal: Format code using `black`

### ISSUE THREAD

**Issue by tarkatronic** [actmd/zoomus#16]
There is not currently any setup for any kind of linters or formatters, leading to a bit of varying code styles throughout the codebase. I would like to propose that this change to an adoption of the `black` autoformatter. This is becoming effectively the de-facto path in the Python ecosystem, and will even be used against certain parts of the stdlib starting soon. In fact, it was even adopted under the official Python org on GitHub: https://github.com/python/black

For more information on the reasons and implications, I would encourage you to read the (accepted) Django Enhancement Proposal for adopting `black`, despite a currently very well fleshed out style guide: https://github.com/django/deps/blob/master/accepted/0008-black.rst

**Comment by prschmid** [comment]
@tarkatronic sounds like a great idea! Let's get the V2 PR (https://github.com/actmd/zoomus/pull/11) merged, and then add this as the next "feature".

**Comment by tarkatronic** [comment]
@prschmid Hey Patrick! I've started up a branch for this work and I realized there is one potentially controversial thing with `black` which I want to get out in the open first, and get a consensus on. The default line length with `black` is 88. Some information on why can be found [in the docs](https://black.readthedocs.io/en/stable/the_black_code_style.html#line-length).

So my question to you is, would you like to maintain what `flake8` is currently configured to use, at 119, or use the default of 88?

I will say, I have been an advocate of 119 for many years now, but I have started using 88 with projects where I'm using `black`, and I really haven't noticed any difference. I don't have to deal with any of the formatting; it's all handled for me. So it doesn't change my own practices in the least. Except for making them easier, really.

**Comment by prschmid** [comment]
I do many projects using 80 characters per line, so 88 will be 10% more than I'm used to. 😄 So, not a problem regarding line length. Thanks for making so many improvements to this project!

**Comment by tarkatronic** [comment]
Great! This is a pretty easy one so I'll try to ship it today. :)

And it's my pleasure; it's nice to have a project to which I can contribute!

**Comment by prschmid** [comment]
Thanks to to the work by @tarkatronic this issue has been addressed.
