### ISSUE TITLE
get b char on every line

### ISSUE THREAD

**Issue by landychev** [actmd/zoomus#17]
`client = ZoomClient(os.environ['zoom-api-key'],os.environ['zoom-api-password'], version=2)

users = client.user.list()
for user in users:
    print(user)`

When pulling user list i get the character b on every line.

`b'{"page_count":37,"page_number":1,"page_size":30,"total_records":1107,"users":[{"id":"1tlFftmeSuKg","first_name":"Malin'
b'","last_name":"Manta","email":"malin.se","type":3,"pmi":84658,"timezone":"","verified":0,"dept":"","creat'
b'ed_at":"2018-04-25T11:08:59Z","last_login_time":"2019-09-02T12:51:18Z","last_client_version":"4.4.55383.0716(android)","status":'
b'"active"},{"id":"YExi-6Vr3zlxOzw","first_name":"Aleksei","last_name":"Landhev","email":"aleksehev@.se","type"'`

**Comment by prschmid** [comment]
This looks to be a decoding issue. Please see this StackOverflow thread: https://stackoverflow.com/questions/16748083/suppress-print-without-b-prefix-for-bytes-in-python-3

**Comment by landychev** [comment]
Thx for the help.
