### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by landychev** [actmd/zoomus#18]
Example Usage
Create the client v2 (default)
As Zoom's default is now the V2 API, the client will default to the V2 version of the API.

```
from zoomus import ZoomClient

client = ZoomClient('API_KEY', 'API_SECRET')

for user in json.loads(client.user.list())['users']:
    user_id = user['id']
    print client.meeting.list('host_id': user_id)
```
Does not work, returns invalid syntax. 

This however will return 1 page size = 30
```
save = []
users = client.user.list()
for user in users:
    save.append(user.decode())

for items in save:
    print(items)
```
As i can see most methods does not work with example supplied. 
Maybe rewrite syntax of example for easy understanding how to use with the methods bellow ?

Best regard Alex

**Comment by prschmid** [comment]
@landychev I apologize for the example not working! I have updated the documentation in 48730144d815d4217ab09b031d203720a8cdcb39. I hope that clarifies things!
