### ISSUE TITLE
Doesn't support the "type" parameter in meetings.list

### ISSUE THREAD

**Issue by malshoff** [actmd/zoomus#21]
When I run this:
`topics = json.loads(client.meeting.list(user_id="USERID").content)`

It shows all of the user's scheduled meetiings (Default should be live according to the api docs). I can add any random arguments after user_id and it does nothing, including the "Type" request parameter.

When I run this:
`topics = json.loads(client.meeting.list(user_id="USERID",type="live").content)`
It does not change the output at all. I can also add arguments that don't even exist and it ignores them rather than giving an error.

https://marketplace.zoom.us/docs/api-reference/zoom-api/meetings/meetings

**Comment by prschmid** [comment]
Hi @malshoff . Sorry to hear you're running in to issues. As each of the methods returns a `Response` object, can you inspect it to see what you are actually sending. E.g.

```python
response = client.meeting.list(user_id="USERID",type="live")
print(response.request.url)
```

If things are correct, then you should see your ``user_id`` and ``type`` parameters passed in the URL string above.

**Comment by malshoff** [comment]
Hey @prschmid thanks for the reply, and sorry for the late response! Looks like the request was sent, I just wasn't getting the expected response, which is no fault of the library. Thanks!
