### ISSUE TITLE
client.meeting.create() fails using v2

### ISSUE THREAD

**Issue by belfazt** [actmd/zoomus#38]
The call returns a response with a 400 status code whenever using the version 2 of the API.

```
>>> zoom_client = ZoomClient('MY_API_KEY', 'MY_API_SECRET', version=2)
>>> response = zoom_client.meeting.create(
...                 user_id=host_id,
...                 start_time=pendulum.now(),
...                 type=2,
...                 duration=60
...             )
>>> response
<Response [400]>
>>> response.content
'{"code":300,"message":"Request Body should be a valid JSON object."}'
>>> response.status_code
400
```

Using V1

```
>>> version = 1
>>> zoom_client = ZoomClient(credentials.api_key, credentials.api_secret, version=version)
>>> response = zoom_client.meeting.create(
...                 host_id=host_id,
...                 start_time=pendulum.now(),
...                 type=2,
...                 duration=60
...             )
>>> response = zoom_client.meeting.create(
...                 host_id=host_id,
...                 start_time=pendulum.now(),
...                 type=2,
...                 duration=60,
...                 topic='string'
...             )
>>> response
<Response [200]>
>>> response.status_code
200
>>> response.content
'{"uuid":"xxxxxxxxxxxx==","id":xxxxxxxx,"host_id":"xxxxxxxxx-xxxxx", ...
,"topic":"string","created_at":"2019-12-30T21:30:11Z"}'
```

**Comment by belfazt** [comment]
I'll try to spend some time to fix it, adding the issue in case someone is on the same boat or if I don't fix it

**Comment by prschmid** [comment]
Hi @belfazt ! Sorry to hear that there is a bug! Could you take a look at the actual data being sent to Zoom's API via the V2 client? I quickly looked at the code and it looks like it should work.... There are a variety of ways you could check what is being sent, but the quickest/dirtiest way would be to put some print statements in the `post_request` method in the [ApiClient](https://github.com/actmd/zoomus/blob/7fa5e23ea987b2effc6c9dbc5597db07e82f96bf/zoomus/util.py#L85) base class. Let me know what you find and I can help you push through a fix. Thanks for your effort!

**Comment by belfazt** [comment]
Thanks a lot for the guidance, I'll try it out :)

**Comment by Shamanyu** [comment]
@belfazt Hey, do you have an update here? Looks like the 'client.webinar.create' is also failing in V2.

**Comment by belfazt** [comment]
Hi, no, I haven't been able to invest time on this

**Comment by pd-9560** [comment]
@Shamanyu @belfazt This is because all the data is being sent as query parameter to post_request method from the create method. This data should be confidential and must be sent as request data. Sending the data as request body will solve the issue. Also, set "Content-Type" to "application/json" in headers of the request.

**Comment by fnadirli** [comment]
please fix this

**Comment by prschmid** [comment]
Thank you for submitting this issue! This should be resolved in the most recent release: https://github.com/actmd/zoomus/releases/tag/1.1.2
