### ISSUE TITLE
User creation does not work. Error 300: Request Body should be a valid JSON object.

### ISSUE THREAD

**Issue by MinistrBob** [actmd/zoomus#54]
I use this code, and I get error
```
from zoomus import ZoomClient
import json
import PASSWORDS
import requests
import time
import jwt

url = "https://api.zoom.us/v2/users"
client = ZoomClient(PASSWORDS.logins['zoom_api_key'], PASSWORDS.logins['zoom_api_secret'])

user = {
    "action": "string",
    "user_info": {
        "email": "string",
        "type": "integer",
        "first_name": "string",
        "last_name": "string",
        "password": "string"
    }
}

user['action'] = "autoCreate"
user['user_info']['email'] = "test777_test777@givinschool.org"
user['user_info']['type'] = 1
user['user_info']['first_name'] = "Дмитрий"
user['user_info']['last_name'] = "Салтыков Щедрин"
user['user_info']['password'] = "ANps11CDkz"
print(f"user={user}")
user_json = json.dumps(user)
print(f"user josn={user_json}")

response = client.user.create(**user)

print(response.text)
print(f"respons={response}")
print(f"respons.headers={response.headers}")
print(f"respons.request.headers={response.request.headers}")
print(f"respons.request.path_url={response.request.path_url}")
print(f"respons.text={response.text}")
print(f"respons.url={response.url}")
print(f"response.status_code={response.status_code}")
```
I took the finished code from Code Generation from https://marketplace.zoom.us/docs/api-reference/zoom-api/users/usercreate and changed it a little. And it work.

```
from zoomus import ZoomClient
import json
import PASSWORDS
import requests
import time
import jwt


def generate_jwt(key, secret):
    header = {"alg": "HS256", "typ": "JWT"}

    payload = {"iss": key, "exp": int(time.time() + 3600)}

    token = jwt.encode(payload, secret, algorithm="HS256", headers=header)
    return token.decode("utf-8")


url = "https://api.zoom.us/v2/users"
client = ZoomClient(PASSWORDS.logins['zoom_api_key'], PASSWORDS.logins['zoom_api_secret'])

user = {
    "action": "string",
    "user_info": {
        "email": "string",
        "type": "integer",
        "first_name": "string",
        "last_name": "string",
        "password": "string"
    }
}

user['action'] = "autoCreate"
user['user_info']['email'] = "test777_test777@givinschool.org"
user['user_info']['type'] = 1
user['user_info']['first_name'] = "Дмитрий"
user['user_info']['last_name'] = "Салтыков Щедрин"
user['user_info']['password'] = "ANps11CDkz"
print(f"user={user}")
user_json = json.dumps(user)
print(f"user josn={user_json}")

myjwt = generate_jwt(PASSWORDS.logins['zoom_api_key'], PASSWORDS.logins['zoom_api_secret'])
bearer = f"Bearer {myjwt}"
payload = user_json
headers = {
    'authorization': bearer,
    'content-type': "application/json"
}

response = requests.request("POST", url, data=payload, headers=headers)

print(response.text)
print(f"respons={response}")
print(f"respons.headers={response.headers}")
print(f"respons.request.headers={response.request.headers}")
print(f"respons.request.path_url={response.request.path_url}")
print(f"respons.text={response.text}")
print(f"respons.url={response.url}")
print(f"response.status_code={response.status_code}") 
```
I think that there is a difference in the format of the data sent, but I just can not understand what this difference is.

**Comment by nils-** [comment]
I think it has to do with zoom API create not using 'params but using body I.E 'data' to create users.
(I've not testing it but I think that the issue)

https://marketplace.zoom.us/docs/api-reference/zoom-api/users/usercreate

https://github.com/actmd/zoomus/blob/7fa5e23ea987b2effc6c9dbc5597db07e82f96bf/zoomus/components/user.py#L46

But i think it should be using data = kwargs ( prob needs to be converted to json from dictionary first).

**Comment by ton77v** [comment]
There is the same problem with client.webinar.register()

**Comment by ton77v** [comment]
> I think it has to do with zoom API create not using 'params but using body I.E 'data' to create users.
> (I've not testing it but I think that the issue)
> 
> https://marketplace.zoom.us/docs/api-reference/zoom-api/users/usercreate
> 
> https://github.com/actmd/zoomus/blob/7fa5e23ea987b2effc6c9dbc5597db07e82f96bf/zoomus/components/user.py#L47
> 
> But i think it should be using data = kwargs ( prob needs to be converted to json from dictionary first).

Right, should use data=kwargs (can use a normal dict) 
Also should add 'content-type': "application/json" to the headers

In my case I resolved the problem the following way:

`def register_webinar_attendee(client, webinar_id, user_data):
    try:
        result = client.webinar.post_request(
                "/webinars/{}/registrants".format(webinar_id), data=user_data,
                headers={
                    "Authorization": "Bearer {}".format(client.config.get("token")),
                    'content-type': "application/json"
                }
            )
    except:
       ...
    return result`

**Comment by Palaing** [comment]
Same for UserComponentV2 -> update : works with  **data=kwargs** instead of  params=kwargs

**Comment by prschmid** [comment]
Hi all! Thank you for finding these bugs and trying to come up with a fix for them! I really appreciate it! 

As you can imagine, things are a little hectic at the moment, and I haven't had the time to work on this to solve the issues that everyone is facing. 

If someone were to create a branch and a PR for the fixes, I will make it a top priority to review it and get the fixed release out.

**Comment by prschmid** [comment]
Thank you for submitting this issue! This should be resolved in the most recent release: https://github.com/actmd/zoomus/releases/tag/1.1.2
