### ISSUE TITLE
util->patch_request V2 need modification

### ISSUE THREAD

**Issue by wonghk** [actmd/zoomus#59]
The patch_request under util need a patch, just add the following before the return statement, otherwise a call to user.update will failed as data should be encoded as application/json 

_**headers['content-type'] = 'application/json'**_ 
return requests.patch(.......

**Comment by Palaing** [comment]
Thank you @wongkh; I met this issue too and solved it changing the line above return statement with:

> headers = {"Authorization": "Bearer {}".format(self.config.get("token")), "Content-Type": "application/json"}

Yet the user.update still did not work, I'll open a ticket for that one

**Comment by prschmid** [comment]
Hi all! Thank you for finding these bugs and trying to come up with a fix for them! I really appreciate it! 

As you can imagine, things are a little hectic at the moment, and I haven't had the time to work on this to solve the issues that everyone is facing. 

If someone were to create a branch and a PR for the fixes, I will make it a top priority to review it and get the fixed release out.

**Comment by xezpeleta** [comment]
I added a PR to fix this issue. Meanwhile, you can use the following workaround:

```python
'''
Change user type (using directly patch_request with custom headers)
'''
def user_update_type(client, user_id, user_type):
    user_data = {
        "type": user_type
    }

    try:
        result = client.user.patch_request(
            "/users/{}".format(user_id), data=user_data, headers={
                "Authorization": "Bearer {}".format(client.config.get("token")),
                "Content-Type": "application/json"
            }
        )
    except:
        return False
    
    if result.status_code == 204:
        return True
    else:
        print("ERROR: cannot assign the license. More info: {}".format(response.text))
        return False
```

**Comment by prschmid** [comment]
Thank you for submitting this issue! This should be resolved in the most recent release: https://github.com/actmd/zoomus/releases/tag/1.1.2
