### ISSUE TITLE
v2 authentication

### ISSUE THREAD

**Issue by pmusolino-rms** [actmd/zoomus#6]
Not sure if this is still being actively developed, but are there any plans to add support for JWT and V2?  
It requires python-jose and adding the token to the authorziation header.

```
from jose import jwt
key = 'APIKEY'
secret = 'APISECRET'

token = jwt.encode({'key': 'value'}, 'secret', algorithm='HS256')
```

**Comment by prschmid** [comment]
Hi @pmusolino-rms ! Could you submit a pull request? I'll happily review it and make a new release.

**Comment by tomasgarzon** [comment]
Hi, here https://github.com/actmd/zoomus/pull/10, we have added support for Zoom API V2, with authentication based on JWT.

**Comment by prschmid** [comment]
@pmusolino-rms We've officially merged in V2 support and made it the default with #11. A new official release is coming shortly! Sorry for the delay!
