### ISSUE TITLE
client.user.create() not working

### ISSUE THREAD

**Issue by niteshrawat1995** [actmd/zoomus#69]
here is my code:
def create_zoom_user(client, user={}):
    user['action'] = "create"
    user['user_info']['email'] = "test777_test777@givinschool.org"
    user['user_info']['type'] = 1
    user['user_info']['first_name'] = "chirag"
    user['user_info']['last_name'] = "mittal"
    user['user_info']['password'] = "password@123"
    print(f"user={user}")
    user_json = json.dumps(user)
    print(f"user josn={user_json}")

    response = client.user.create(**user)

output : {"code":300,"message":"Request Body should be a valid JSON object."}

PS: why is  the user_dict send to the api in params rather than data , is it desirable ?
refrence point: 
class UserComponentV2(base.BaseComponent):
     def create(self, **kwargs):
        return self.post_request("/users", params=kwargs) # kwargs = by send data

**Comment by prschmid** [comment]
Hello @niteshrawat1995 . Thank you for submitting this issue! This should be resolved in the most recent release: https://github.com/actmd/zoomus/releases/tag/1.1.2

**Comment by lrhazi** [comment]
Funny how client.user.create() needs the kwarg action='create' to be passed to it. No?
