### ISSUE TITLE
Client.meeting.list takes one arguement, two were given

### ISSUE THREAD

**Issue by maxhar** [actmd/zoomus#9]
just started using zoomus with python3, passing host_id to the client.meeting.list() method like this

params = {'host_id' : "myhostid'}
client.meeting.list(params)

but it raises exception like this 

TypeError: list() takes 1 positional argument but 2 were given.

i am trying to run the code given in readme.MD .. but it aint working. tried it with python2 as well. same error

**Comment by maxhar** [comment]
Never mind, was passing the kwargs wrong. but the documentation provided on github is not enough had to use hit and trial instead. where can i find the detailed docs

**Comment by prschmid** [comment]
I apologize for there not being enough documentation -- there are examples of how to use things in the unit tests.

Feel free to put together a pull request with more documentation and I'll gladly approve it!
